### ISSUE TITLE
Build fails in tez-ui 

### ISSUE THREAD

**Issue by sonia-garudi** [OpenPOWER-BigData/HDP2.5-tez#1]
**Project** - tez-ui
**Error Stacktrace** -
[INFO] --- exec-maven-plugin:1.3.2:exec (ember build) @ tez-ui ---
module.js:327
   throw err;
   ^
Error: Cannot find module '/ws/tez-release/tez-ui/src/main/webapp/node/npm/bin/npm-cli'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Function.Module.runMain (module.js:441:10)
   at startup (node.js:139:18)
   at node.js:968:3

**RCA** - The path to npm-cli in the pom.xml is incorrect:
`<argument>node/npm/bin/npm-cli</argument>`

**Comment by sonia-garudi** [comment]
Following change in tez-ui/pom.xml resolved the issue:

```
      @@ -152,7 +152,7 @@
-                <argument>node/npm/bin/npm-cli</argument>
+                <argument>node/node_modules/npm/bin/npm-cli</argument>
```

Same error occurs for '**ember test**' as well which is resolved by following change in tez-ui/pom.xml:

```
      @@ -169,7 +169,7 @@
-                <argument>node/npm/bin/npm-cli</argument>
+               <argument>node/node_modules/npm/bin/npm-cli</argument>
```

**Comment by asanjar** [comment]
why it does not fail on x86?

**Comment by sonia-garudi** [comment]
It is occurring on x86 as well. We have made the changes in order to resolve the issue.

**Comment by ayappanec** [comment]
I guess since we are updating node & npm to higher version , we are facing this issue. With the default node & npm version in pom.xml file , we won't face this problem.

**Comment by ayappanec** [comment]
I haven't faced this issue on x86.

**Comment by sonia-garudi** [comment]
On x86, with the default versions (i.e. frontend-maven-plugin 0.0.23, node v0.12.2 , npm 2.15.3 and phantomjs 1.9.19), this error did not occur.

After changing the frontend-maven-plugin version to 1.1, the build failed with the same error:

```
[INFO] --- exec-maven-plugin:1.3.2:exec (ember build) @ tez-ui ---
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/tez-release/tez-ui/src/main/webapp/node/npm/bin/npm-cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
